[workspace]
members = [
    "chacha20",
    "hc-256",
    "rabbit",
    "rc4",
    "salsa20",
    "pulp-wrapper",
    "cipher-suite",
    "asm-macros",
    "tmp",
]
resolver = "2"

[profile.dev]
opt-level = 2

[profile.release]
debug = true
