[workspace]
members = ["chacha20", "hc-256", "rabbit", "rc4", "salsa20", "pulp-wrapper"]
resolver = "2"

[profile.dev]
opt-level = 2

[profile.release]
debug = true

[patch.crates-io]
inout = { git = 'https://github.com/Zeegomo/utils', rev = "54528796038c80795f1dc4b53e228f79f7897611" }
