[package]
name = "pulp-wrapper"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cty = "*"
cipher = "*"
pulp_sdk_rust = { git = " https://github.com/Zeegomo/pulp-sdk-rust" }
generic-array = "*"
